{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "\n",
    "\"\"\"planets.py: Simulating the trajectory of the six solar planets around the sun in the solar system.\n",
    "\n",
    "__author__ = \"Shanye\"\n",
    "__pkuid__  = \"1800011804\"\n",
    "__email__  = \"shan26_0v0@126.com\"\n",
    "\"\"\"\n",
    "\n",
    "import math\n",
    "\n",
    "import turtle\n",
    "\n",
    "def main():\n",
    "    #Set up the screen.\n",
    "    wn=turtle.Screen()\n",
    "    wn.screensize(2000,1500)\n",
    "\n",
    "    #Set up the Sun.\n",
    "    Sun = turtle.Pen()\n",
    "    Sun.hideturtle()\n",
    "    Sun.home()\n",
    "    Sun.dot(25,\"orange\")\n",
    "\n",
    "    #Set up the Mercury.\n",
    "    Mercury = turtle.Pen()\n",
    "    Mercury.penup()\n",
    "    Mercury.shape(\"circle\")\n",
    "    Mercury.shapesize(0.75)\n",
    "    Mercury.color(\"blue\",\"blue\")\n",
    "    Mercury.goto(70,0)\n",
    "    Mercury.pendown()\n",
    "\n",
    "    #Set up the Venus.\n",
    "    Venus = turtle.Pen()\n",
    "    Venus.penup()\n",
    "    Venus.shape(\"circle\")\n",
    "    Venus.color(\"yellow\",\"yellow\")\n",
    "    Venus.goto(140,0)\n",
    "    Venus.pendown()\n",
    "\n",
    "    #Set up the Earth.\n",
    "    Earth = turtle.Pen()\n",
    "    Earth.penup()\n",
    "    Earth.shape(\"circle\")\n",
    "    Earth.color(\"green\",\"green\")\n",
    "    Earth.goto(210,0)\n",
    "    Earth.pendown()\n",
    "\n",
    "    #Set up the Mars.\n",
    "    Mars = turtle.Pen()\n",
    "    Mars.penup()\n",
    "    Mars.shape(\"circle\")\n",
    "    Mars.color(\"red\",\"red\")\n",
    "    Mars.goto(280,0)\n",
    "    Mars.pendown()\n",
    "\n",
    "    #Set up the Jupiter.\n",
    "    Jupiter = turtle.Pen()\n",
    "    Jupiter.penup()\n",
    "    Jupiter.shape(\"circle\")\n",
    "    Jupiter.shapesize(2)\n",
    "    Jupiter.color(\"brown\",\"brown\")\n",
    "    Jupiter.goto(420,0)\n",
    "    Jupiter.pendown()\n",
    "\n",
    "    #Set up the Saturn.\n",
    "    Saturn = turtle.Pen()\n",
    "    Saturn.penup()\n",
    "    Saturn.shape(\"circle\")\n",
    "    Saturn.shapesize(1.8)\n",
    "    Saturn.color(\"black\",\"black\")\n",
    "    Saturn.goto(560,0)\n",
    "    Saturn.pendown()\n",
    "\n",
    "    #Let the planets move.\n",
    "    for i in range(1,1000):    \n",
    "        Mercury.goto(50*math.cos(0.1*i)+20,40*math.sin(0.1*i))\n",
    "        Venus.goto(100*math.cos(0.08*i)+40,80*math.sin(0.08*i))\n",
    "        Earth.goto(150*math.cos(0.06*i)+60,120*math.sin(0.06*i))\n",
    "        Mars.goto(200*math.cos(0.04*i)+80,160*math.sin(0.04*i))\n",
    "        Jupiter.goto(300*math.cos(0.02*i)+120,240*math.sin(0.02*i))\n",
    "        Saturn.goto(400*math.cos(0.01*i)+160,320*math.sin(0.01*i))\n",
    "\n",
    "    turtle.down()\n",
    "\n",
    "    \n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
